# Generated by Django 3.2 on 2024-11-28 00:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la verdura')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El valor no puede ser negativo')], verbose_name='Precio')),
                ('tipo_alimento', models.IntegerField(choices=[('Envasado', 'Productos envasados'), ('Fruta', 'Manzana, Platano, Kiwi, etc'), ('Verduras', 'Palta, Lechuga, Zanahoria, etc'), ('Carnes', 'Vacuno, Cerdo, Pollo, etc')], verbose_name='Tipo de alimento')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=50)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')])),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_distribuidora', models.CharField(max_length=100, verbose_name='Nombre de la Distribuidora')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Descuento (%)')),
                ('productos', models.ManyToManyField(related_name='sistemas', to='aplicacion.Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='aplicacion.proveedor')),
            ],
        ),
    ]
