# Generated by Django 3.2 on 2024-11-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_alimento',
            field=models.CharField(choices=[('Envasado', 'Productos envasados'), ('Fruta', 'Manzana, Platano, Kiwi, etc'), ('Verduras', 'Palta, Lechuga, Zanahoria, etc'), ('Carnes', 'Vacuno, Cerdo, Pollo, etc')], max_length=10, verbose_name='Tipo de alimento'),
        ),
    ]
